# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NYC UX Holiday Party
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Get ready to join the greater New York UX community as we kick off the holiday season. Join us again this year and come share some UX stories over a drink or two, re-connect with old and make connections anew, perhaps find a new gig for the upcoming year but most of all enjoy some holiday cheer!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jonathanpberger
github_username:  jonathanpberger

# Build settings
markdown: kramdown
